[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.511896+00:00] request.INFO: Matched route "contao_managerapi_server_database__invoke". {"route":"contao_managerapi_server_database__invoke","route_parameters":{"_route":"contao_managerapi_server_database__invoke","_controller":"_ContaoManager\\Contao\\ManagerApi\\Controller\\Server\\DatabaseController"},"request_uri":"http://localhost:8086/public/contao-manager.phar.php/api/server/database","method":"GET"} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.551936+00:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":4} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.558594+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.560228+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.561915+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.563063+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.563071+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.577772+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.579304+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.579330+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.595741+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[22-Mar-2024 15:18:22 UTC] [2024-03-22T15:18:22.614689+00:00] app.ERROR: Uncaught PHP Exception _ContaoManager\Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at phar:///var/www/html/public/contao-manager.phar.php/api/EventListener/ExceptionListener.php line 88 {"exception":"[object] (_ContaoManager\\Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at phar:///var/www/html/public/contao-manager.phar.php/api/EventListener/ExceptionListener.php:88)\n[previous exception] [object] (_ContaoManager\\Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at phar:///var/www/html/public/contao-manager.phar.php/vendor/symfony/security-http/Firewall/AccessListener.php:113)"} []
